import { useState } from 'react';
import { Eye, EyeOff, House, Leaf } from 'lucide-react';
import { sendPasswordResetEmail, signInWithEmailAndPassword } from 'firebase/auth';
import { auth, isConfigured } from '../firebase/firebase';
export default function Login() {
  const [email,setEmail]=useState(''), [password,setPassword]=useState(''), [show,setShow]=useState(false), [loading,setLoading]=useState(false), [error,setError]=useState(''), [resetOpen,setResetOpen]=useState(false), [message,setMessage]=useState('');
  const submit=async e=>{e.preventDefault();setLoading(true);setError('');try{await signInWithEmailAndPassword(auth,email,password);}catch{setError('Неверная электронная почта или пароль.');setLoading(false);}};
  const reset=async e=>{e.preventDefault();setLoading(true);setError('');setMessage('');try{await sendPasswordResetEmail(auth,email);setMessage('Письмо для восстановления пароля отправлено на вашу почту.');setResetOpen(false);}catch(err){setError(err.code==='auth/invalid-email'?'Введите корректный email.':'Не удалось отправить письмо. Проверьте email и попробуйте снова.');}finally{setLoading(false)}};
  return <main className="login-page"><section className="login-photo"><div className="login-quote"><Leaf/><p>Баланс начинается с пространства, в котором слышно себя.</p></div></section><section className="login-panel"><form className="login-card" onSubmit={resetOpen?reset:submit}><div className="login-brand"><House/><span>Дом баланса</span></div><h1>{resetOpen?'Восстановление пароля':'С возвращением'}</h1><p>{resetOpen?'Мы отправим ссылку на вашу почту':'Войдите в своё тихое пространство'}</p>{!isConfigured && <div className="setup-note"><b>Firebase ещё не настроен.</b><br/>Добавьте параметры проекта в файл <code>.env</code>.</div>}<label><span>Электронная почта</span><input type="email" value={email} onChange={e=>setEmail(e.target.value)} required disabled={!isConfigured}/></label>{!resetOpen&&<label><span>Пароль</span><div className="password"><input type={show?'text':'password'} value={password} onChange={e=>setPassword(e.target.value)} required disabled={!isConfigured}/><button type="button" onClick={()=>setShow(!show)} aria-label="Показать пароль">{show?<EyeOff/>:<Eye/>}</button></div></label>}{error&&<p className="error">{error}</p>}{message&&<p className="success">{message}</p>}<button className="btn login-btn" disabled={loading||!isConfigured}>{loading?'Подождите…':resetOpen?'Отправить письмо':'Войти'}</button><button className="text-btn" type="button" onClick={()=>{setResetOpen(!resetOpen);setError('')}}>{resetOpen?'Вернуться ко входу':'Забыли пароль?'}</button></form></section></main>;
}
