import { useMemo, useState } from 'react';
import * as I from 'lucide-react';
import Modal from './Modal';
import { createItem, deleteItem, toggleHabitForDate, updateItem } from '../firebase/firestore';

const today = () => new Date().toISOString().slice(0,10);
const formatDate = d => d ? new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'long'}).format(new Date(d+'T12:00:00')) : 'Без срока';
const sectionMap = {
  'Сегодня': { collection:'tasks', add:'Добавить дело', empty:'Здесь пока нет дел. Добавьте первое маленькое действие.', fields:[['title','Название','text',true],['description','Описание','textarea'],['date','Дата','date'],['time','Время','time'],['priority','Приоритет','select'],['category','Категория'],['projectId','Проект (ID)']] },
  'Проекты': { collection:'projects', add:'Новый проект', empty:'Здесь пока нет проектов. Создайте первый проект, который хочется довести до результата.', fields:[['title','Название','text',true],['description','Описание','textarea'],['status','Статус','select'],['progress','Прогресс, %','number'],['deadline','Дедлайн','date']] },
  'Идеи': { collection:'ideas', add:'Новая идея', empty:'Поймайте мысль, пока она рядом.', fields:[['title','Название','text',true],['text','Текст','textarea'],['category','Категория'],['pinned','Закреплено','select']] },
  'Заметки': { collection:'notes', add:'Новая заметка', empty:'Ваше спокойное место для важных мыслей.', fields:[['title','Название','text',true],['text','Текст','textarea'],['category','Категория'],['pinned','Закреплено','select']] },
  'Библиотека': { collection:'resources', add:'Добавить материал', empty:'Соберите здесь книги, статьи и курсы, к которым хочется возвращаться.', fields:[['title','Название','text',true],['type','Тип','select'],['description','Описание','textarea'],['url','Ссылка','url'],['tags','Теги']] },
  'Цели': { collection:'goals', add:'Новая цель', empty:'Сформулируйте первую цель — спокойно и честно.', fields:[['title','Название','text',true],['description','Описание','textarea'],['progress','Прогресс, %','number'],['deadline','Дедлайн','date'],['status','Статус','select']] },
};
const options = { priority:['Обычный','Важный','Высокий'], status:['Активна','На паузе','Завершена'], pinned:['Нет','Да'], type:['Книга','Статья','Курс','Подкаст','Видео','Ссылка'] };
const makeFields = rows => rows.map(([name,label,type='text',required=false])=>({name,label,type,required,wide:type==='textarea',options:options[name]}));

export function Dashboard({ data, setPage, name, quote }) {
  const tasks=data.tasks.filter(x=>x.date===today()), done=tasks.filter(x=>x.completed).length, pct=tasks.length?Math.round(done/tasks.length*100):0;
  const cards=[
    ['Сегодня',I.Sun,`${pct}% дня завершено`,tasks.slice(0,4).map(x=>x.title), 'Сегодня'],
    ['Проекты',I.FolderKanban,`${data.projects.filter(x=>x.status!=='Завершена').length} активных`,data.projects.slice(0,4).map(x=>`${x.title} · ${x.progress||0}%`),'Проекты'],
    ['Привычки',I.Repeat2,`${data.habits.length} привычек`,data.habits.slice(0,4).map(x=>x.title),'Привычки'],
    ['Библиотека',I.BookOpen,`${data.resources.length} материалов`,data.resources.slice(0,3).map(x=>x.title),'Библиотека'],
    ['Идеи',I.Lightbulb,`${data.ideas.length} идей`,data.ideas.slice(0,2).map(x=>x.title),'Идеи'],
    ['Размышления',I.MessageCircleHeart,`${data.reflections.length} записей`,data.reflections.slice(0,1).map(x=>x.gratitude),'Размышления'],
    ['Календарь',I.CalendarDays,formatDate(today()),data.events.slice(0,3).map(x=>x.title),'Календарь'],
    ['Заметки',I.NotebookPen,`${data.notes.length} заметок`,data.notes.slice(0,3).map(x=>x.title),'Заметки'],
    ['Цели',I.Target,`${data.goals.length} целей`,data.goals.slice(0,3).map(x=>`${x.title} · ${x.progress||0}%`),'Цели']
  ];
  const hour=new Date().getHours(), greet=hour<12?'Доброе утро':hour<18?'Добрый день':'Добрый вечер';
  return <><header className="hero"><div><p className="eyebrow">ВАШЕ ПРОСТРАНСТВО</p><h1>{greet}, {name} <span>❧</span></h1><p>Ваш день — ваш выбор. Двигайтесь к балансу шаг за шагом.</p></div><blockquote>{quote}</blockquote></header><section className="dashboard-grid">{cards.map(([title,Icon,badge,items,target],i)=><article className={`dash-card c${i}`} key={title} role="button" tabIndex="0" onClick={()=>setPage(target)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setPage(target)}}}><div className="card-title"><Icon/><h2>{title}</h2><span>{badge}</span></div><div className="card-content">{items.length?items.map((x,j)=><div className="mini-row" key={j}><i/>{x}</div>):<p>Здесь пока тихо — самое время начать.</p>}</div><span className="card-link">Открыть раздел <I.ArrowRight/></span></article>)}</section><footer className="balance-note"><I.House/><p>Баланс рождается из маленьких решений,<br/>которые вы принимаете каждый день.</p><I.Sprout/></footer></>;
}

export function CollectionPage({ page, uid, items }) {
  const cfg=sectionMap[page], [modal,setModal]=useState(null), [query,setQuery]=useState(''), [confirm,setConfirm]=useState(null);
  const shown=items.filter(x=>JSON.stringify(x).toLowerCase().includes(query.toLowerCase()));
  const save=async form=> modal?.id?updateItem(uid,cfg.collection,modal.id,form):createItem(uid,cfg.collection,{...form,completed:false});
  return <section className="page-section"><div className="page-head"><div><p className="eyebrow">ДОМ БАЛАНСА</p><h1>{page}</h1><p>{cfg.empty}</p></div><button className="btn" onClick={()=>setModal({})}><I.Plus/> {cfg.add}</button></div><div className="toolbar"><I.Search/><input placeholder="Поиск в разделе" value={query} onChange={e=>setQuery(e.target.value)}/></div>{shown.length===0?<div className="empty"><I.Sprout/><h2>Пока здесь просторно</h2><p>{cfg.empty}</p><button className="btn" onClick={()=>setModal({})}>{cfg.add}</button></div>:<div className="item-grid">{shown.map(x=><article className="item-card" key={x.id}><div className="item-top"><span>{x.category||x.type||x.status||'Личное'}</span><div><button onClick={()=>setModal(x)} aria-label="Редактировать"><I.Pencil/></button><button onClick={()=>setConfirm(x)} aria-label="Удалить"><I.Trash2/></button></div></div><h2>{x.title}</h2><p>{x.description||x.text||'Без описания'}</p>{page==='Сегодня'&&<label className="check"><input type="checkbox" checked={!!x.completed} onChange={e=>updateItem(uid,'tasks',x.id,{completed:e.target.checked})}/><span>{x.completed?'Выполнено':x.time||'Без времени'}</span></label>}{['Проекты','Цели'].includes(page)&&<div className="progress"><i style={{width:`${x.progress||0}%`}}/><span>{x.progress||0}%</span></div>}<small>{formatDate(x.date||x.deadline)}</small></article>)}</div>}{modal&&<Modal title={modal.id?'Редактировать':cfg.add} fields={makeFields(cfg.fields)} initial={modal} onClose={()=>setModal(null)} onSave={save}/>} {confirm&&<div className="confirm"><div><h3>Удалить «{confirm.title}»?</h3><p>Это действие нельзя отменить.</p><button className="btn ghost" onClick={()=>setConfirm(null)}>Отмена</button><button className="btn danger" onClick={async()=>{await deleteItem(uid,cfg.collection,confirm.id);setConfirm(null)}}>Удалить</button></div></div>}</section>;
}

export function Habits({uid,data}){const [modal,setModal]=useState(null);const days=useMemo(()=>{const a=[];for(let i=0;i<7;i++){const d=new Date();d.setDate(d.getDate()-((d.getDay()+6)%7)+i);a.push(d.toISOString().slice(0,10));}return a},[]);return <section className="page-section"><div className="page-head"><div><p className="eyebrow">МАЛЕНЬКИЕ ШАГИ</p><h1>Привычки</h1><p>Неделя, в которой важна не идеальность, а возвращение.</p></div><button className="btn" onClick={()=>setModal({})}><I.Plus/> Новая привычка</button></div>{data.habits.length===0?<div className="empty"><I.Repeat2/><h2>Начните с одной привычки</h2><p>Небольшое действие, которое поддержит вас каждый день.</p></div>:<div className="habit-table"><div className="habit-row head"><b>Привычка</b>{days.map(d=><span key={d}>{new Intl.DateTimeFormat('ru',{weekday:'short'}).format(new Date(d))}</span>)}</div>{data.habits.map(h=><div className="habit-row" key={h.id}><b>{h.title} <button onClick={()=>setModal(h)} aria-label="Редактировать"><I.Pencil/></button><button onClick={()=>deleteItem(uid,'habits',h.id)} aria-label="Удалить"><I.Trash2/></button></b>{days.map(d=>{const log=data.habitLogs.find(l=>l.habitId===h.id&&l.date===d),on=!!log?.completed;return <button className={on?'day on':'day'} key={d} onClick={()=>toggleHabitForDate(uid,h.id,d,!on)} aria-label={`${h.title}, ${d}`}><I.Check/></button>})}</div>)}</div>}{modal&&<Modal title={modal.id?'Редактировать привычку':'Новая привычка'} initial={modal} fields={makeFields([['title','Название','text',true],['category','Категория'],['targetPerWeek','Раз в неделю','number']])} onClose={()=>setModal(null)} onSave={f=>modal.id?updateItem(uid,'habits',modal.id,f):createItem(uid,'habits',{...f,active:true})}/>}</section>}

export function Reflections({uid,items}){const [modal,setModal]=useState(false);return <section className="page-section"><div className="page-head"><div><p className="eyebrow">ТИХИЙ ЖУРНАЛ</p><h1>Размышления</h1><p>Место, где можно честно услышать себя.</p></div><button className="btn" onClick={()=>setModal(true)}><I.Plus/> Новая запись</button></div><div className="reflection-grid">{items.map(x=><article className="reflection" key={x.id}><span>{x.mood||'Спокойно'} · {formatDate(x.date)}</span><h3>Сегодня получилось</h3><p>{x.wins}</p><h3>Я благодарна</h3><p>{x.gratitude}</p></article>)}</div>{!items.length&&<div className="empty"><I.Feather/><h2>Чистая страница</h2><p>Запишите то, что хочется сохранить от сегодняшнего дня.</p></div>}{modal&&<Modal title="Новая запись" fields={makeFields([['date','Дата','date',true],['mood','Настроение'],['wins','Что сегодня получилось?','textarea'],['gratitude','За что я благодарна?','textarea'],['thoughts','О чём я думаю?','textarea'],['improvement','Что можно улучшить?','textarea']])} onClose={()=>setModal(false)} onSave={f=>createItem(uid,'reflections',f)}/>}</section>}

export function CalendarPage({uid,data}){const [cursor,setCursor]=useState(new Date()),[selected,setSelected]=useState(today()),[modal,setModal]=useState(false);const year=cursor.getFullYear(),month=cursor.getMonth(),first=(new Date(year,month,1).getDay()+6)%7,count=new Date(year,month+1,0).getDate();const cells=[...Array(first).fill(null),...Array.from({length:count},(_,i)=>i+1)];return <section className="page-section"><div className="page-head"><div><p className="eyebrow">РИТМ МЕСЯЦА</p><h1>Календарь</h1><p>Планы и события в одном спокойном ритме.</p></div><button className="btn" onClick={()=>setModal(true)}><I.Plus/> Событие</button></div><div className="calendar-layout"><div className="month-card"><div className="month-head"><button onClick={()=>setCursor(new Date(year,month-1))}><I.ChevronLeft/></button><h2>{new Intl.DateTimeFormat('ru',{month:'long',year:'numeric'}).format(cursor)}</h2><button onClick={()=>setCursor(new Date(year,month+1))}><I.ChevronRight/></button></div><div className="calendar-grid">{'Пн Вт Ср Чт Пт Сб Вс'.split(' ').map(x=><b key={x}>{x}</b>)}{cells.map((n,i)=>n?<button key={i} className={`${selected===`${year}-${String(month+1).padStart(2,'0')}-${String(n).padStart(2,'0')}`?'selected ':''}${data.events.some(e=>e.date===`${year}-${String(month+1).padStart(2,'0')}-${String(n).padStart(2,'0')}`)?'marked':''}`} onClick={()=>setSelected(`${year}-${String(month+1).padStart(2,'0')}-${String(n).padStart(2,'0')}`)}>{n}</button>:<i key={i}/>)}</div></div><aside className="agenda"><h2>{formatDate(selected)}</h2>{[...data.tasks,...data.events].filter(x=>x.date===selected).map(x=><div key={x.id}><span>{x.time||x.startTime||'Весь день'}</span><b>{x.title}</b></div>)}{![...data.tasks,...data.events].some(x=>x.date===selected)&&<p>На этот день планов пока нет.</p>}</aside></div>{modal&&<Modal title="Новое событие" fields={makeFields([['title','Название','text',true],['date','Дата','date',true],['startTime','Начало','time'],['endTime','Окончание','time'],['category','Категория'],['description','Описание','textarea']])} initial={{date:selected}} onClose={()=>setModal(false)} onSave={f=>createItem(uid,'events',f)}/>}</section>}

export function Insights({page,data}){const done=data.tasks.filter(x=>x.completed).length,total=data.tasks.length,hits=data.habitLogs.filter(x=>x.completed).length,active=data.projects.filter(x=>x.status!=='Завершена').length,pct=total?Math.round(done/total*100):0;return <section className="page-section"><div className="page-head"><div><p className="eyebrow">ВАШ РИТМ</p><h1>{page}</h1><p>Честный взгляд на движение без давления и оценок.</p></div></div><div className="stats"><article><I.CircleCheckBig/><b>{done}</b><span>задач выполнено</span></article><article><I.ChartPie/><b>{pct}%</b><span>общий прогресс</span></article><article><I.Flame/><b>{hits}</b><span>отметок привычек</span></article><article><I.FolderHeart/><b>{active}</b><span>активных проектов</span></article></div><div className="chart-card"><h2>Прогресс проектов</h2>{data.projects.length?data.projects.map(x=><div className="chart-row" key={x.id}><span>{x.title}</span><div><i style={{width:`${x.progress||0}%`}}/></div><b>{x.progress||0}%</b></div>):<p>Данные появятся после создания проектов.</p>}</div></section>}
